const {test,expect}=require('@playwright/test');
const path=require('path');
test.use({channel:'chrome'});
const iss={OBJECT_NAME:'ISS (ZARYA)',OBJECT_ID:'1998-067A',EPOCH:'2026-09-07T11:57:47.376864',MEAN_MOTION:15.49018229,ECCENTRICITY:.00049836,INCLINATION:51.6306,RA_OF_ASC_NODE:252.7093,ARG_OF_PERICENTER:115.8922,MEAN_ANOMALY:244.258,EPHEMERIS_TYPE:0,CLASSIFICATION_TYPE:'U',NORAD_CAT_ID:25544,ELEMENT_SET_NO:999,REV_AT_EPOCH:58451,BSTAR:.00010434666,MEAN_MOTION_DOT:.00005306,MEAN_MOTION_DDOT:0};
const start=Date.parse('2026-09-06T00:00Z')/1000;
const hourly={time:Array.from({length:264},(_,i)=>start+i*3600)};
for(const [key,value]of Object.entries({cloud_cover:12,cloud_cover_low:5,cloud_cover_mid:0,cloud_cover_high:7,visibility:30000,precipitation:0,relative_humidity_2m:60,weather_code:0,temperature_2m:20}))hourly[key]=Array(264).fill(value);
async function boot(page,{offline=false}={}){const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource'))errors.push(m.text());});await page.clock.setFixedTime(new Date('2026-09-07T18:00Z'));await page.route('**/api/analytics/**',r=>r.fulfill({status:204,body:''}));await page.route('**celestrak.org/**',r=>r.fulfill({json:offline?{error:'Unavailable'}:[iss]}));await page.route('**api.open-meteo.com/**',r=>r.fulfill({json:offline?{error:'Unavailable'}:{timezone:'America/Chicago',hourly}}));await page.goto(`file://${path.resolve('overhead.html')}`);await page.waitForFunction(()=>window.__OVERHEAD_TEST__&&!__OVERHEAD_TEST__.state.busy);return errors;}
test('all widths, seven nights, sky chart, favorite, settings and saved sites',async({page})=>{const errors=await boot(page);for(const width of [390,768,1024,1440,1920]){await page.setViewportSize({width,height:950});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.locator('#headline')).not.toBeEmpty();}
 await page.getByRole('tab',{name:'NEXT 7 DAYS'}).click();await expect(page.locator('#week button')).toHaveCount(7);await page.locator('[data-day="1"]').click();await page.locator('.event').first().click();await expect(page.locator('#detail-title')).toContainText('ISS');await expect(page.locator('#detail-content svg')).toBeVisible();await page.getByRole('button',{name:'Favorite spacecraft'}).click();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('overhead.favorites')))).toEqual(['25544']);await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('[name="minimum"]').selectOption('30');await page.locator('[name="clock"]').selectOption('24');await page.getByRole('button',{name:'Apply settings'}).click();await page.waitForFunction(()=>!__OVERHEAD_TEST__.state.busy);expect(await page.evaluate(()=>__OVERHEAD_TEST__.state.settings.minimum)).toBe('30');
 await page.locator('#location-open').click();await page.getByRole('button',{name:'Save current location'}).click();await page.getByRole('button',{name:'Save current location'}).click();await expect(page.locator('.saved-row')).toHaveCount(1);await page.getByRole('button',{name:'Delete saved Princeton, Indiana'}).click();await expect(page.locator('.saved-row')).toHaveCount(0);await page.keyboard.press('Escape');
 await page.getByRole('tab',{name:'NOW',exact:true}).click();await expect(page.locator('#night-label')).toContainText('NEXT TWO HOURS');expect(errors).toEqual([]);
});
test('API failures never create events; import restores real orbital calculation',async({page})=>{const errors=await boot(page,{offline:true});await expect(page.locator('.event')).toHaveCount(0);await expect(page.locator('#headline')).toContainText('data isn’t');await expect(page.locator('#night-score')).toHaveText('—');await page.locator('#diagnostics summary').click();await page.locator('#import').setInputFiles({name:'iss.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify([iss]))});await page.waitForFunction(()=>!__OVERHEAD_TEST__.state.busy);await expect(page.locator('.event').first()).toBeVisible();expect(await page.evaluate(()=>Object.values(__OVERHEAD_TEST__.state.results).flat().every(p=>p.provisional))).toBe(true);expect(errors).toEqual([]);});
test('stale cache survives network failure, then clearing cache removes downloaded data',async({page})=>{await boot(page);await page.evaluate(()=>new Promise((resolve,reject)=>{const r=indexedDB.open('overhead-cache',1);r.onsuccess=()=>{const tx=r.result.transaction('responses','readwrite'),s=tx.objectStore('responses'),q=s.getAll();q.onsuccess=()=>q.result.forEach(row=>s.put({...row,at:Date.now()-86400000}));tx.oncomplete=resolve;tx.onerror=reject;};}));await page.route('**celestrak.org/**',r=>r.fulfill({json:{error:'Unavailable'}}));await page.route('**api.open-meteo.com/**',r=>r.fulfill({json:{error:'Unavailable'}}));await page.reload();await page.waitForFunction(()=>window.__OVERHEAD_TEST__&&!__OVERHEAD_TEST__.state.busy);await expect(page.locator('.event').first()).toBeVisible();await expect(page.locator('#freshness')).toContainText('STALE');await page.locator('#diagnostics summary').click();await page.getByRole('button',{name:'Clear downloaded cache'}).click();await expect(page.locator('#status')).toContainText('cache cleared');await page.reload();await page.waitForFunction(()=>window.__OVERHEAD_TEST__&&!__OVERHEAD_TEST__.state.busy);await expect(page.locator('.event')).toHaveCount(0);});
