#!/usr/bin/env python3
"""Prepare compact EPA Level III geography. Offline build, no runtime service.
uv run --with pyshp --with shapely --with pyproj tools/build-fruiting-ecoregions.py /tmp/us_eco_l3.zip
"""
import argparse
import hashlib
import json
import zipfile
from pathlib import Path
import shapefile
from pyproj import CRS, Transformer
from shapely.geometry import shape, mapping
from shapely.ops import transform, unary_union

SOURCE = 'https://dmap-prod-oms-edc.s3.us-east-1.amazonaws.com/ORD/Ecoregions/us/us_eco_l3.zip'
ROOT = Path(__file__).resolve().parents[1]

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('archive', type=Path)
    parser.add_argument('--tolerance', type=float, default=0.01, help='Simplification degrees (~1 km); approximate boundaries')
    args = parser.parse_args()
    with zipfile.ZipFile(args.archive) as z:
        reader = shapefile.Reader(shp=z.open('us_eco_l3.shp'), shx=z.open('us_eco_l3.shx'), dbf=z.open('us_eco_l3.dbf'), encoding='latin1')
        crs = CRS.from_wkt(z.read('us_eco_l3.prj').decode())
        project = Transformer.from_crs(crs, 4326, always_xy=True).transform
        groups, names = {}, {}
        for record in reader.iterShapeRecords():
            p = record.record.as_dict()
            code = str(p['US_L3CODE'])
            names[code] = p['US_L3NAME']
            groups.setdefault(code, []).append(shape(record.shape.__geo_interface__))
    features = []
    for code in sorted(groups, key=int):
        geom = transform(project, unary_union(groups[code])).simplify(args.tolerance, preserve_topology=True)
        features.append({'type':'Feature','properties':{'code':code,'name':names[code]},'bbox':list(geom.bounds),'geometry':mapping(geom)})
    def rounded(value):
        if isinstance(value, float): return round(value, 5)
        if isinstance(value, (list, tuple)): return [rounded(v) for v in value]
        if isinstance(value, dict): return {k:rounded(v) for k,v in value.items()}
        return value
    features = rounded(features)
    data = {'type':'FeatureCollection','version':'epa-l3-2015-simplified-v1','source':SOURCE,'sourceSha256':hashlib.sha256(args.archive.read_bytes()).hexdigest(),'toleranceDegrees':args.tolerance,'boundaryCaution':'Approximate boundaries; near-boundary assignments require verification.','features':features}
    out = ROOT / 'data/fruiting-forecast/ecoregions.json'
    out.write_text(json.dumps(data,separators=(',',':'))+'\n')
    # Local script also works in file:// preview; data remains authoritative JSON.
    (out.parent/'ecoregions.js').write_text('/* Generated by tools/build-fruiting-ecoregions.py; EPA attribution in JSON. */\nwindow.FF_ECOREGIONS='+out.read_text().strip()+';\n')
    print(f'{len(features)} ecoregions; {out.stat().st_size:,} bytes')

if __name__ == '__main__':
    main()
