#!/usr/bin/env python3
"""Prepare compact U.S. state geography for collecting-rule jurisdiction. Offline build.

Collecting-rule scoping must never guess a property's state from a property name or a
manager string, and must never let one state's permission leak across a state line.
This geography gives the app an authoritative, offline, deterministic jurisdiction
lookup by point. It is used only for rule scoping, not for biology.

    uv run --with pyshp --with shapely --with pyproj tools/build-fruiting-states.py /tmp/cb_2023_us_state_20m.zip

Boundaries are simplified, so a property within roughly the tolerance of a state line
can resolve to the neighbor state. That failure is conservative: the state-scoped rule
does not match, and the property stays UNKNOWN_VERIFY instead of inheriting a rule.
"""
import argparse
import hashlib
import json
import zipfile
from pathlib import Path

import shapefile
from pyproj import CRS, Transformer
from shapely.geometry import shape, mapping
from shapely.ops import transform, unary_union

SOURCE = 'https://www2.census.gov/geo/tiger/GENZ2023/shp/cb_2023_us_state_20m.zip'
ROOT = Path(__file__).resolve().parents[1]
# Territories are retained: rules may one day be scoped to them, and dropping them
# would silently make their public land look jurisdiction-free.
EXCLUDE = {'60', '66', '69', '72', '78'}  # American Samoa, Guam, N. Mariana, PR, Virgin Islands


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('archive', type=Path)
    parser.add_argument('--tolerance', type=float, default=0.02,
                        help='Simplification degrees (~2 km); approximate boundaries')
    args = parser.parse_args()
    with zipfile.ZipFile(args.archive) as z:
        reader = shapefile.Reader(shp=z.open('cb_2023_us_state_20m.shp'), shx=z.open('cb_2023_us_state_20m.shx'),
                                  dbf=z.open('cb_2023_us_state_20m.dbf'), encoding='latin1')
        crs = CRS.from_wkt(z.read('cb_2023_us_state_20m.prj').decode())
        project = Transformer.from_crs(crs, 4326, always_xy=True).transform
        groups = {}
        for record in reader.iterShapeRecords():
            p = record.record.as_dict()
            if p['GEOID'] in EXCLUDE:
                continue
            groups.setdefault((p['STUSPS'], p['NAME']), []).append(shape(record.shape.__geo_interface__))
    features = []
    for (code, name) in sorted(groups):
        geom = transform(project, unary_union(groups[(code, name)])).simplify(args.tolerance, preserve_topology=True)
        features.append({'type': 'Feature', 'properties': {'code': code, 'name': name},
                         'bbox': list(geom.bounds), 'geometry': mapping(geom)})

    def rounded(value):
        if isinstance(value, float):
            return round(value, 5)
        if isinstance(value, (list, tuple)):
            return [rounded(v) for v in value]
        if isinstance(value, dict):
            return {k: rounded(v) for k, v in value.items()}
        return value

    data = {'type': 'FeatureCollection', 'version': 'us-census-state-2023-simplified-v1', 'source': SOURCE,
            'sourceSha256': hashlib.sha256(args.archive.read_bytes()).hexdigest(),
            'toleranceDegrees': args.tolerance,
            'boundaryCaution': ('Simplified state boundaries; a property within about the tolerance of a state '
                                'line can resolve to the neighbor state and then keeps UNKNOWN_VERIFY rather '
                                'than inheriting another state\'s collecting rule.'),
            'purpose': 'Collecting-rule jurisdiction scoping only. Not ecological geography.',
            'features': rounded(features)}
    out = ROOT / 'data/fruiting-forecast/states.json'
    out.write_text(json.dumps(data, separators=(',', ':')) + '\n')
    (out.parent / 'states.js').write_text('/* Generated by tools/build-fruiting-states.py; US Census attribution in JSON. */\n'
                                          'window.FF_STATES=' + out.read_text().strip() + ';\n')
    print(f'{len(features)} states/territories; {out.stat().st_size:,} bytes JSON, '
          f'{(out.parent / "states.js").stat().st_size:,} bytes JS')


if __name__ == '__main__':
    main()